module.exports = [
  {
    firstName: '',
    lastName: '',
    username: 'Brian Chen',
    email: 'bchen@travelx.com',
    password: 'password01',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Max Alexander',
    email: 'malexander@travelx.com',
    password: 'password02',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Edward Burrow',
    email: 'eburrows@travelx.com',
    password: 'password03',
  },
  {
    firstName: '',
    lastName: '',
    username: 'David Thomas',
    email: 'dthomas@travelx.com',
    password: 'password04',
  },
  {
    firstName: '',
    lastName: '',
    username: 'James Berard',
    email: 'jberard@travelx.com',
    password: 'password05',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Alan Zurack',
    email: 'azurack@travelx.com',
    password: 'password06',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Donald Barner',
    email: 'dbarner@travelx.com',
    password: 'password07',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Garima Sharma',
    email: 'gsharma@travelx.com',
    password: 'password08',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Masahiro Sakuma',
    email: 'msakuma@travelx.com',
    password: 'password09',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Dena Mark',
    email: 'dmark@travelx.com',
    password: 'password10',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Maria Kardava',
    email: 'mkardava@travelx.com',
    password: 'password01',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Josh Kasi',
    email: 'jkasi@travelx.com',
    password: 'password02',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Diana Ahmed',
    email: 'dahmed@travelx.com',
    password: 'password03',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Igor Korman',
    email: 'ikorman@travelx.com',
    password: 'password04',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Jeff Grasso',
    email: 'jgrasso@travelx.com',
    password: 'password05',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Konstantin Smirnov',
    email: 'ksmirnov@travelx.com',
    password: 'password06',
  },
  {
    firstName: '',
    lastName: '',
    username: 'George Sanders',
    email: 'gsanders@travelx.com',
    password: 'password07',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Nidhi Patel',
    email: 'npatel@travelx.com',
    password: 'password08',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Valaria Alarcon',
    email: 'valarcon@travelx.com',
    password: 'password09',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Evince Edward ',
    email: 'eedouard@travelx.com',
    password: 'password10',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Charles Beck',
    email: 'cbeck@travelx.com',
    password: 'password01',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Chen Chen',
    email: 'cchen@travelx.com',
    password: 'password02',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Erica Choi',
    email: 'echoi@travelx.com',
    password: 'password03',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Vivian Crib',
    email: 'vcrib@travelx.com',
    password: 'password04',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Adiba Ejaz',
    email: 'aejaz@travelx.com',
    password: 'password05',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Hugo Hamilton',
    email: 'hhamilton@travelx.com',
    password: 'password06',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Rawan Hayat',
    email: 'rhayat@travelx.com',
    password: 'password07',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Samuel Howe',
    email: 'showe@travelx.com',
    password: 'password08',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Stanley Jian',
    email: 'sjian@travelx.com',
    password: 'password09',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Daniel Joo',
    email: 'djoo@travelx.com',
    password: 'password10',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Justin Lee',
    email: 'jlee@travelx.com',
    password: 'password01',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Brian Love',
    email: 'blove@travelx.com',
    password: 'password02',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Ioana Lia',
    email: 'iliad@travelx.com',
    password: 'password03',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Sebastian Rossi',
    email: 'srossi@travelx.com',
    password: 'password04',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Collin Wang',
    email: 'cwang@travelx.com',
    password: 'password05',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Ashley Waller',
    email: 'awaller@travelx.com',
    password: 'password06',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Collin Wang',
    email: 'cwang@travelx.com',
    password: 'password07',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Jacob Weinstein',
    email: 'jweinstein@travelx.com',
    password: 'password08',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Je Seung You',
    email: 'jseung@travelx.com',
    password: 'password09',
  },
  {
    firstName: '',
    lastName: '',
    username: 'Ribhav Talwar',
    email: 'rtalwar@travelx.com',
    password: 'password10',
  },
];
